on: [ pull_request ]
name: Roave
jobs:
  roave_bc_check:
    name: Roave BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga

