on: [ pull_request ]
name: Roave
jobs:
  roave_bc_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 7.4

      - name: Install roave/backward-compatibility-check.
        run: composer require --dev roave/backward-compatibility-check

      - name: Run roave/backward-compatibility-check.
        run: vendor/bin/roave-backward-compatibility-check
